language: java
sudo: false
jdk:
  - oraclejdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: 6c892850-d440-4836-88a6-660c9eae8254
  app:
    develop: foodry-dev
    master: foodry
